name: Check News and Send Notification

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  run-news-checker:
    # نطلب من GitHub إنه يوفر لنا جهاز افتراضي     بيفتح مؤقتًا عشان ينفذ المهمة ويقفل لوحده بعدها.
    runs-on: ubuntu-latest
    steps:
      # عشان يدخل على الريبو بتاعتك ويسحب نسخة من كل ملفاتك
      - name: Checkout repository
        uses: actions/checkout@v3
      #بينزل Node.js إصدار 18 على الجهاز الافتراضي
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd news-notifier
          npm install

      - name: Run news checker script
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        run: |
          cd news-notifier
          node index.js